#!/usr/bin/env node
/**
 * SCORM 1.2 packaging for help centres.
 *
 * It does NOT re-author the content. It takes the page that `helpcentre.js` already
 * built and wraps it, so the module in the LMS and the page on the web can never say
 * different things — rebuild, repackage, done. That is the whole point: a SCORM that
 * carries its own copy of the copy is a snapshot that starts drifting the day someone
 * edits the JSON.
 *
 * Opt in per flow with "scorm": true in helpcentres/<partner>/<flow>.json.
 *
 *   node scripts/scorm.js            # package every flow that opted in
 *   node scripts/scorm.js forest/help-centre
 *
 * Output: dist-scorm/<partner>-<flow>/  and  dist-scorm/<partner>-<flow>.zip
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const HC_DIR = path.join(ROOT, 'helpcentres');
const DIST = path.join(ROOT, 'dist');
const OUT = path.join(ROOT, 'dist-scorm');
const SCO_DIR = path.join(ROOT, 'engine', 'scorm');
const SCHEMAS = ['imscp_rootv1p1p2.xsd', 'adlcp_rootv1p2.xsd', 'imsmd_rootv1p2p1.xsd', 'ims_xml.xsd'];

const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
function fail(msg) { console.error(`  ✗ ${msg}`); process.exit(1); }

/** SCORM identifiers must not contain spaces or start with a digit. */
function ident(prefix, partner, flow) {
  const slug = `${partner}_${flow}`.replace(/[^A-Za-z0-9_]/g, '_').toUpperCase();
  return `${prefix}_${slug}`;
}

function discover(only) {
  const out = [];
  if (!fs.existsSync(HC_DIR)) return out;
  for (const partner of fs.readdirSync(HC_DIR)) {
    const pdir = path.join(HC_DIR, partner);
    if (!fs.statSync(pdir).isDirectory()) continue;
    for (const f of fs.readdirSync(pdir)) {
      if (!f.endsWith('.json')) continue;
      const cfg = readJson(path.join(pdir, f));
      const flow = cfg.flow || f.replace(/\.json$/, '');
      if (only && `${partner}/${flow}` !== only) continue;
      if (!only && cfg.scorm !== true) continue;
      out.push({ partner, flow, cfg });
    }
  }
  return out;
}

/**
 * Which sections must be seen before the module counts as complete.
 * Defaults to the two the module was asked to cover; a config can override.
 */
function sides(cfg) {
  if (Array.isArray(cfg.scormSides)) return cfg.scormSides;
  // Every section is a checkpoint. Two coarse ones could be scrolled past in seconds and
  // still counted as "seen"; one per section makes the progress bar mean something and
  // makes reaching the end a requirement rather than a suggestion.
  const list = (cfg.sections || [])
    .filter((s) => s.id && s.title)
    .map((s) => ({ id: s.id, label: (s.navLabel || s.title).replace(/&[a-z]+;/g, '').trim() }));
  if (!list.length) fail('no sections to track — set "scormSides" in the config');
  return list;
}

function build({ partner, flow, cfg }) {
  const src = path.join(DIST, partner, flow, 'index.html');
  if (!fs.existsSync(src)) fail(`build the pages first — missing ${path.relative(ROOT, src)}`);

  let html = fs.readFileSync(src, 'utf8');

  const panel = fs.readFileSync(path.join(SCO_DIR, 'completion.html'), 'utf8');
  const logic = fs.readFileSync(path.join(SCO_DIR, 'completion.js'), 'utf8')
    .replace('__SCO_SIDES__', JSON.stringify(sides(cfg)));

  // The completion panel goes at the end of <main>, inline — never a fixed-position
  // modal, which is what breaks inside LMS iframes.
  const closeMain = html.lastIndexOf('</main>');
  if (closeMain < 0) fail('no </main> in the built page');
  html = html.slice(0, closeMain) + panel + '\n' + html.slice(closeMain);

  html = html.replace('</body>',
    `<script src="scorm_api.js"></script>\n<script>\n${logic}\n</script>\n</body>`);

  // The page links out to the live web version; inside an LMS those must escape the frame.
  html = html.replace(/<a class="card"/g, '<a class="card" target="_blank" rel="noopener"');
  html = html.replace(/<a class="card vid"/g, '<a class="card vid" target="_blank" rel="noopener"');
  html = html.replace(/<a class="url"/g, '<a class="url" target="_blank" rel="noopener"');

  const dir = path.join(OUT, `${partner}-${flow}`);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'index.html'), html);
  fs.copyFileSync(path.join(SCO_DIR, 'scorm_api.js'), path.join(dir, 'scorm_api.js'));
  for (const s of SCHEMAS) fs.copyFileSync(path.join(SCO_DIR, s), path.join(dir, s));

  const title = cfg.scormTitle || cfg.fdTitle || cfg.h1;
  const files = ['index.html', 'scorm_api.js', ...SCHEMAS];
  const manifest = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  ${title}
  Generated by scripts/scorm.js from dist/${partner}/${flow}/index.html — do not hand-edit.
  Rebuild the page, re-run the packager.

  Completion: the SCO reports "completed" only when the learner presses "Mark as complete",
  which unlocks once every tracked section has been on screen. It never reports a terminal
  status on load, and beforeunload/pagehide commit rather than finish. No masteryscore is
  declared: this is a reference module, not a scored assessment.
-->
<manifest identifier="com.coachesvoice.${partner}.${flow.replace(/[^a-z0-9]/gi, '')}" version="1.0"
  xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
  xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                      http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>
  <organizations default="${ident('ORG', partner, flow)}">
    <organization identifier="${ident('ORG', partner, flow)}">
      <title>${title}</title>
      <item identifier="${ident('ITEM', partner, flow)}" identifierref="${ident('RES', partner, flow)}" isvisible="true">
        <title>${title}</title>
      </item>
    </organization>
  </organizations>
  <resources>
    <resource identifier="${ident('RES', partner, flow)}" type="webcontent" adlcp:scormtype="sco" href="index.html">
${files.map((f) => `      <file href="${f}"/>`).join('\n')}
    </resource>
  </resources>
</manifest>
`;
  fs.writeFileSync(path.join(dir, 'imsmanifest.xml'), manifest);

  // ── validate before zipping ──
  const man = fs.readFileSync(path.join(dir, 'imsmanifest.xml'));
  if (man[0] === 0xEF) fail('manifest has a BOM');
  if (!man.toString('utf8').startsWith('<?xml')) fail('manifest does not start with <?xml');
  for (const f of files) {
    if (!fs.existsSync(path.join(dir, f))) fail(`manifest lists ${f} but it is not on disk`);
  }
  // Well-formedness, then targeted structural checks.
  //
  // NOT full XSD validation: `xmllint --schema imscp_rootv1p1p2.xsd` cannot resolve the
  // adlcp namespace when handed a single schema, and ADL's own ims_xml.xsd trips its
  // namespace check. Verified against the EFL package, which imported into the LMS
  // successfully and fails that same command — so a failure there is a false alarm.
  // These checks catch what actually breaks an import instead.
  try {
    execSync('xmllint --noout imsmanifest.xml', { cwd: dir, stdio: 'pipe' });
  } catch (e) {
    const msg = (e.stderr || e.stdout || '').toString().trim();
    if (/command not found|not recognized/i.test(msg)) console.warn('  ! xmllint unavailable — XML not parsed');
    else fail(`manifest is not well-formed XML:\n${msg}`);
  }

  const xml = man.toString('utf8');
  const need = (re, what) => { if (!re.test(xml)) fail(`manifest: ${what}`); };
  need(/<schema>ADL SCORM<\/schema>/, 'missing <schema>ADL SCORM</schema>');
  need(/<schemaversion>1\.2<\/schemaversion>/, 'missing <schemaversion>1.2</schemaversion>');
  need(/adlcp:scormtype="sco"/, 'resource is not declared as a SCO');

  for (const id of xml.match(/identifier(?:ref)?="([^"]+)"/g) || []) {
    const val = id.split('"')[1];
    if (/\s/.test(val)) fail(`identifier "${val}" contains a space`);
    if (/^[0-9]/.test(val)) fail(`identifier "${val}" starts with a digit`);
  }
  const orgDefault = (xml.match(/<organizations default="([^"]+)"/) || [])[1];
  if (!xml.includes(`<organization identifier="${orgDefault}"`)) fail(`organizations/@default "${orgDefault}" has no matching organization`);
  const ref = (xml.match(/identifierref="([^"]+)"/) || [])[1];
  if (!xml.includes(`<resource identifier="${ref}"`)) fail(`identifierref "${ref}" has no matching resource`);
  const href = (xml.match(/<resource[^>]*href="([^"]+)"/) || [])[1];
  if (!fs.existsSync(path.join(dir, href))) fail(`resource href "${href}" is not on disk`);

  const zip = path.join(OUT, `${partner}-${flow}.zip`);
  fs.rmSync(zip, { force: true });
  execSync(`zip -q -r "${zip}" . -x '.*' -x '__MACOSX/*'`, { cwd: dir });

  const kb = (fs.statSync(zip).size / 1024).toFixed(0);
  console.log(`    ✓ dist-scorm/${partner}-${flow}.zip (${kb}KB) — tracks ${sides(cfg).map(s => s.id).join(' + ')}`);
  return 1;
}

const only = process.argv[2];
const targets = discover(only);
if (!targets.length) {
  console.log(only ? `\nNo help centre matches "${only}".`
                   : '\nNo help centre has "scorm": true — nothing to package.');
  process.exit(0);
}
console.log(`\nSCORM packages — ${targets.length}\n`);
fs.mkdirSync(OUT, { recursive: true });
let n = 0;
for (const t of targets) { console.log(`  → ${t.partner}/${t.flow}`); n += build(t); }
console.log(`\nDone — ${n} package(s). Upload the .zip as a SCORM lesson item.`);
